config/routes.rb
Rails.application.routes.draw do
  root 'pages#home'
  get '/createroom' => 'rooms#new'
  post '/createroom' => 'rooms#create'

  get 'join' => 'pages#join'
  get 'help' => 'pages#help'
  get 'home' => 'pages#home'
  
  get 'join' => 'guests#new'
  post 'join' => 'guests#create'

  get 'login' => 'moderators#new'
  post 'login' => 'moderators#create'

  get 'guest' => 'queue#guestQueue'
  get 'mod' => 'moderators#modQueue'
  
  post 'next' => 'moderators#next'

  post 'shutdown' => 'moderators#shutdown'

  mount ActionCable.server, at: '/cable'

  resources :guests, :moderators, :rooms

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/guest.rb
class Guest < ApplicationRecord
    validates :accessCode, presence: true, length: { is: 6 }
    belongs_to :room, foreign_key: "accessCode"
end

app/models/moderator.rb
class Moderator < ApplicationRecord
    validates :name, presence: true, length: { maximum: 50 }
    validates :accessCode, presence: true, length: { is: 6 }
    belongs_to :room, foreign_key: "accessCode"
    validates_uniqueness_of :name, :scope => :accessCode

    attr_accessor :virtual_password #virtual attribute that is not saved to the DB
end

app/models/room.rb
class Room < ApplicationRecord
    validates :accessCode, presence: true, length: { is: 6 }, uniqueness: true
    validates :password, presence: true

    #when room is deleted that is associated with certain guests and moderators, they will be deleted too
    has_many :guest, dependent: :destroy 
    has_many :moderator, dependent: :destroy

    self.primary_key = "accessCode"
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    protect_from_forgery with: :exception
    include GuestsHelper
    include ModeratorsHelper


end

app/controllers/guests_controller.rb
class GuestsController < ApplicationController
    def create
        @guest = Guest.new(guest_params)
        @mod = Moderator.new #need to create a new mod in case we get redirected back to join - guests/join requires it for form

        if !Room.exists?(@guest.accessCode)
            @guest.errors.add(:accessCode, message: "Cannot find access code.")
            render 'pages/join'
        elsif !@guest.save
            render 'pages/join'
        else
            log_in_guest @guest
            redirect_to guest_url
        end
    end

    private

        def guest_params
            params.require(:guest).permit(:accessCode)
        end
end

app/controllers/moderators_controller.rb
class ModeratorsController < ApplicationController
    

    def create
        @mod = Moderator.new(mod_params)
        @guest = Guest.new ##need to create a new mod in case we get redirected back to join - guests/join requires it for form

        if !Room.exists?(@mod.accessCode)
            @mod.errors.add(:accessCode, message: "Cannot find access code.")
            render 'pages/join'
        elsif Room.find(@mod.accessCode).password != @mod.virtual_password
            @mod.errors.add(:virtual_password, message: "Password is not correct.")
            render 'pages/join'
        elsif !@mod.save
            render 'pages/join'
        else
            log_in_mod @mod
            redirect_to mod_url
        end
    end

    def modQueue
        
    end

    def shutdown
        @mod = Moderator.find_by(id: session[:moderator_id]);
        @guest = Guest.find_by(id: session[:guest_id]);
        
        guestsInQueue =  Guest.where(accessCode: @mod.accessCode)
        if guestsInQueue.size > 0
            ActionCable.server.broadcast "moderators_channel_#{@mod.accessCode}", modName: @mod.name #broadcast that Queue is shut down
        end
        Room.delete((@mod.accessCode))
        redirect_to join_url
    end

    def next
        @mod = Moderator.find_by(id: session[:moderator_id]);
        guestsInQueue = Guest.where(accessCode: @mod.accessCode)
        if guestsInQueue.size > 0
            logger.debug guestsInQueue.order(:created_at).first
            guestsInQueue.order(:created_at).first.destroy #remove next person from the queue 
            ActionCable.server.broadcast "queue_channel_#{@mod.accessCode}", modName: @mod.name #broadcast mod name so it can be displayed if user pos is 1
        end
    end
    

        def mod_params
            params.require(:moderator).permit(:name, :accessCode, :virtual_password)
        end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
    def home
    end

    #temporary landing page for both Moderator and Guest when they log in for now

    def join
        @guest = Guest.new
        @mod = Moderator.new
    end
end

app/controllers/queue_controller.rb
class QueueController < ApplicationController
    before_action :check_guest_logged_in, only: [:guestQueue]
    before_action :check_mod_logged_in, only: [:modQueue]
    
    def modQueue
    end

 
    def guestQueue
        #this should be changed so it's based on the current position relative to everyone else
        @initialPos = Guest.where(accessCode: Guest.find_by(id: cookies.signed[:guest_id]).accessCode).size.to_s 
    end
    
    private
        def check_guest_logged_in
            unless guest_logged_in?
                redirect_to home_url
            end
        end

        def check_mod_logged_in
            unless mod_logged_in?
                redirect_to home_url
            end
        end
end

app/controllers/rooms_controller.rb
class RoomsController < ApplicationController
    #just for showing the accessCode and password once the room is created
    def show
        @room = Room.find(params[:id])
    end
    
    def new
        @room = Room.new #this will be the argument required for the form which accepts the inputted password
    end

    def create
        @room = Room.new(room_params)
        @room.accessCode  = get_unique_accessCode
        if @room.save
            redirect_to @room
        else  
            render 'new' #start process over again
        end
    end

    private

        #returns randomly generated 6 character code
        def generate_accessCode
          return ((0..9).to_a + ("a".."z").to_a).shuffle[0..5].join("")
        end

        #returns a unique access code not saved in DB currently
        def get_unique_accessCode
            code = generate_accessCode
            while Room.exists?(accessCode: code) do
                code = generate_accessCode
            end
            return code
        end

        #ensure that the user only submits a password, not an accessCode
        def room_params
            params.require(:room).permit(:password)
        end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/guests_helper.rb
module GuestsHelper
    def log_in_guest(guest)
        cookies.signed[:guest_id] = guest.id
    end

    def current_guest
        if cookies.signed[:guest_id]
            @current_guest ||= Guest.find_by(id: cookies.signed[:guest_id])
        end
    end

    def guest_logged_in?
        !current_guest.nil?
    end
end

app/helpers/moderators_helper.rb
module ModeratorsHelper

    def log_in_mod(moderator)
        session[:moderator_id] = moderator.id
    end

    def current_mod
        if session[:moderator_id]
            @current_mod ||= Moderator.find_by(id: session[:moderator_id])
        end
    end

    def mod_logged_in?
        !current_mod.nil?
    end
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/queue_helper.rb
module QueueHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/moderators/modQueue.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Moderator</title>
    <link rel="stylesheet" href="../application.css">
    <meta name="viewport" content="width=device-width">
  </head>
  <body>

        <div class="primary-content">
          <%= link_to 'Next', next_path, remote: true, method: :post, rel: "nofollow", :class => "button" %>
          <br>
          <br>
          <button onclick="window.location.href=#" class="button">Push to Back</button>
          <br>
          <br>
          <%= link_to 'Shutdown', shutdown_path, remote: true, method: :post, rel: "nofollow", :class=>"button", data: { confirm: "You sure?" } %>

          <button onclick = "window.location.href='../help.html'" class ="button small-button bottom-corner"> Help </button>
          
        </div><!-- End .primary-content-->

  </body>
</html>



app/views/pages/help.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Help</title>
    <link rel="stylesheet" href="../application.css">
    <meta name="viewport" content="width=device-width">
  </head>
  <body>

        <div class="primary-content">
              <h2>This page is under development.</h2>
        </div><!-- End .primary-content-->

  </body>
</html>

app/views/pages/home.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>EzQueue</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <!-- <link rel="stylesheet" href="css/application.css"> -->
    <meta name="viewport" content="width=device-width">
  </head>

  <body>
    <%= yield %>
    <div class="primary-content">
         <%= link_to "Create", createroom_path, class: "button"%>
        <button onclick="window.location.href='../join.html'" class="button">Join</button>
        <button onclick = "window.location.href='../help.html'" class ="button small-button bottom-corner"> Help </button>

    </div><!-- End .primary-content-->



  </body>
</html>

app/views/pages/join.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Join</title>
    <link rel="stylesheet" href="../application.css">
    <meta name="viewport" content="width=device-width">
  </head>
  <body>

        <div class="primary-content">

            <div class = "form-left">
                <h2>Guest</h2>
                <%= form_for(:guest, url: join_path) do |f| %>
                        <%= render 'shared/guest_error_messages' %>
                        <%= f.text_field :accessCode, class: 'form-control', placeholder: "Access Code" %>
                        <br>
                        <%= f.submit "Join", class: "button small-button" %>
                    <% end %>
            </div>

            <div class = "form-right">
                <h2>Moderator</h2>
                    <%= form_for(:moderator, url: login_path) do |f| %> 
                        <%= render 'shared/mod_error_messages' %>
                        <%= f.text_field :name, class: 'form-control', placeholder: "Name" %>
                        <br>
                        <%= f.text_field :accessCode, class: 'form-control', placeholder: "Access Code" %>
                        <br>
                        <%= f.text_field :virtual_password, class: 'form-control', placeholder: "Password" %>
                        <br>
                        <%= f.submit "Join", class: "button small-button" %>
                    <% end %>
                </div>
                <button onclick = "window.location.href='../help.html'" class ="button small-button bottom-corner"> Help </button>
                
        </div><!-- End .primary-content-->

  </body>
</html>

app/views/pages/modlogin.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Moderator</title>
    <link rel="stylesheet" href="../application.css">
    <meta name="viewport" content="width=device-width">
  </head>
  <body>

        <div class="primary-content">
          <button onclick="window.location.href=#" class="button">Next</button>
          <br>
          <br>
          <button onclick="window.location.href=#" class="button">Push to Back</button>
          <br>
          <br>
          <button onclick="window.location.href=#" class="button">Shutdown</button>
          <button onclick = "window.location.href='../help.html'" class ="button small-button bottom-corner"> Help </button>
          

        </div><!-- End .primary-content-->

  </body>
</html>

app/views/queue/guestQueue.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Guest</title>
    <link rel="stylesheet" href="../application.css">
    <meta name="viewport" content="width=device-width">
  </head>
  <body>

        <div class="primary-content">
            <div id="queue-position" class = "queue-position">
              <%= image_tag("Shteve.PNG", :size => "406x400", :alt => "Steven says you are logged in")%>
              <%= simple_format(@initialPos, id: "guest-position") %>
            </div>
              <br>
              <br>
              <a class="button medium-button" href="../home.html">Back To Home</a>
              <button onclick = "window.location.href='../help.html'" class ="button small-button bottom-corner"> Help </button>
        </div><!-- End .primary-content-->

  </body>
</html>

app/views/rooms/new.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Create</title>
    <link rel="stylesheet" href="../applications.css">
    <meta name="viewport" content="width=device-width">
  </head>
  <body>

        <div class="primary-content">
                <div class = "create-form">
                    <%= form_for(@room) do |f| %>
                        <%= render 'shared/room_error_messages' %>
                        <%= f.text_field :password, class: 'form-control', placeholder: "Password" %>
                        <br>
                        <%= f.submit "Create Queue", class: "button small-button" %>
                    <% end %>
                </div>
                <button onclick = "window.location.href='../help.html'" class ="button small-button bottom-corner"> Help </button>

        </div><!-- End .primary-content-->
    </body>
</html>

app/views/rooms/show.html.erb
<<title>Create</title>
<div class = "primary-content result-display">
  <p>
    Access Code:
  </p>
  <%= @room.accessCode %>
  <br>
  <br>
  <p>
    Password:
  </p>
  <%= @room.password %>
  <br>
  <br>
  <a class="button medium-button" href="../home.html">Back To Home</a>
</div>

app/views/shared/_guest_error_messages.html.erb
<% if @guest.errors.any? %>
  <div id="error_explanation" class = "error">
    <div class="alert alert-danger">
      The form contains <%= pluralize(@guest.errors.count, "error") %>
    </div>
    <ul class = "error-list">
    <% @guest.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

app/views/shared/_mod_error_messages.html.erb
<% if @mod.errors.any? %>
  <div id="error_explanation" class = "error">
    <div class="alert alert-danger">
      The form contains <%= pluralize(@mod.errors.count, "error") %>
    </div>
    <ul class = "error-list">
    <% @mod.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

app/views/shared/_room_error_messages.html.erb
<% if @room.errors.any? %>
  <div id="error_explanation" class = "error">
    <div class="alert alert-danger">
      The form contains <%= pluralize(@room.errors.count, "error") %>
    </div>
    <ul class = "error-list">
    <% @room.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>